name: CI/CD pipeline

on:
  push:
    branches: [dev-pipeline]
  pull_request:

jobs:
  frontend-lint-test:
    name: Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        working-directory: frontend
        run: |
          npm ci --prefer-offline --no-audit
          npm install --save-optional @rollup/rollup-linux-x64-gnu

      - name: Run ESLint
        run: npm run lint
        working-directory: frontend

      - name: Run Prettier check
        run: npm run format
        working-directory: frontend

      - name: Run Vitest
        run: npm run test
        working-directory: frontend

  backend-lint-test:
    name: Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, bcmath
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
        working-directory: backend

      - name: Run Laravel Pint
        run: composer lint
        working-directory: backend

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --stop-on-failure --testdox
        working-directory: backend
